### ISSUE TITLE
Support 'compression parameter in open() and cat(), as in fsspec

### ISSUE THREAD

**Issue by yiga2** [fsspec/gcsfs#431] opened 2021-11-03 16:34 UTC
`fsspec.open()` conveniently decompresses a file upon reading. This is especially useful when using the `infer` value. 

`gcsfs` does not support compressed files on-the-fly.

For example,
```
content = fsspec.open(filename, compression='infer').open().read()
```
cannot be done as a one-liner in `gcsfs` as you need to build a wrapper to handle `gz` or `zip`

Request is to transpose the "transparency" feature from `fsspec` : 
https://filesystem-spec.readthedocs.io/en/latest/features.html#transparent-text-mode-and-compression

Workaround: use `fsspec`...

**Comment by martindurant** [comment] 2021-11-03 16:35
Nearly identical to https://github.com/intake/filesystem_spec/issues/812 (which is for s3fs), with suggested fix in the comments.

**Comment by martindurant** [comment] 2021-11-03 16:41
I should mention that zip is special, because it isn't a compressed stream, but a set of compressed files in a single target - it is *not* supported by `fsspec.open`, but instead by ZipFileSystem; some other files are of this type (tar...), supported by LibArchiveFileSystem.

**Comment by martindurant** [comment] 2021-11-05 17:20
I will close this issue in favour of the other one, which I do intend to get to if someone else doesn't beat me to it.

**Closed by martindurant** 2021-11-05 17:20 UTC

**Comment by TiansuYu** [comment] 2022-01-31 18:28
@martindurant Hi, I would like to kindly report a bug issue directly related with this ticket. Mainly I want to ask if your [PR](https://github.com/fsspec/filesystem_spec/pull/826) actually solved this issue. 

Recently, I have spotted that while `fsspec.open` can read a gzipped json line file but `fsspec.filesytem("gcs").open` failed. Though I cannot directly share with you the dataset (it is produced from spark), still I would like to confirm with you if this is not the issue. 

Here is my code snippet:
```
import fsspec 
url = "gs://xxxx.json.gz"

fs = fsspec.filesystem("gcs")
with fs.open(url, "r", compression="gzip") as f:
    print(f.read())
```

And here is the error message while I use `fs.open`:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
/var/folders/0r/3g66h49s7fv4p732f17fpt3m0000gn/T/ipykernel_78180/4276936585.py in <module>
      4 fs = fsspec.filesystem("gcs")
      5 with fs.open(url, "r", compression="gzip") as f:
----> 6     print(f.read())

~/anaconda3/envs/dat/lib/python3.8/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Using `fsspec.open` has printed my table quite nicely.

**Comment by martindurant** [comment] 2022-02-01 14:27
I can confirm that things appear to be working correctly:
```
In [7]: gcs.cat("mdtemp/file.gz")
Out[7]: b'\x1f\x8b\x08\x00\xbcB\xf9a\x02\xff\xcaH\xcd\xc9\xc9\x07\x00\x00\x00\xff\xff\x03\x00\x86\xa6\x106\x05\x00\x00\x00'

In [8]: import gzip

In [9]: gzip.decompress(_)
Out[9]: b'hello'

In [12]: with gcs.open("mdtemp/file.gz", mode="rt", compression="gzip") as f:
    ...:     print(f.read())
    ...:
hello
```

**Comment by TiansuYu** [comment] 2022-02-02 08:30
I am stil a bit curious about why in your script `gcs` can open a "local file path" `"mdtemp/file.gz"` (correct me if I understood it wrong). 

To make things comparable, I have written this script to generate a josnl.gz file and read it out using two methods. (please modify `path` and `rpath` in your case).

```
import jsonlines
import gzip 
import fsspec

path = "~/Downloads/temp/dummy.json.gz"

d = [{f"dummy{i}": i for i in range(10)} for _ in range(5)] 

def write_jsonl_gzip(path, payload):
    with gzip.open(path, "wb") as fp:
        jsonl_writer = jsonlines.Writer(fp)
        jsonl_writer.write_all(payload)

write_jsonl_gzip(path, d)

# upload to a bucket
gcs = fsspec.filesystem("gcs")
rpath = "gs://xxx/tmp/dummy.jsonl.gz"
gcs.put(path, rpath)

# read the file with fsspec 
with fsspec.open(rpath, "r", compression="gzip") as f:
    print(f.read())

# read the file with gcs 
# gcs = fsspec.filesystem("gcs")
# with gcs.open(rpath, "r", compression="gzip") as f:
#     print(f.read())
```
For me, the `fsspec` one prints the normal content defined as in `d`, but `gcs` throw out a UnicodeDecodeError as expected. Please let me if I have made some mistakes here.

**Comment by martindurant** [comment] 2022-02-02 15:07
> why in your script gcs can open a "local file path"

This was not a local file path - everything in gcsfs refers to remote CGS paths, and including "gcs://" or "gs://" is strictly optional. 

Things still work fine for me:
```
In [2]: import gzip
   ...: import fsspec

In [3]: with gzip.open("temp.gz", "wb") as f:
   ...:     f.write(b'hello')

In [4]: gcs = fsspec.filesystem("gcs")
   ...: rpath = "gs://mdtemp/dummy.gz"
   ...: gcs.put("temp.gz", rpath)

In [5]: with gcs.open(rpath, "r", compression="gzip") as f:
   ...:     print(f.read())
hello
```
